[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # 设置 Node.js 版本
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

# 处理 API 路由
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

# 处理所有其他路由
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"